apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollout
  annotations:
    kubernetes.io/ingress.class: nginx
    # Argo Rollouts가 이 Ingress를 관리하도록 허용
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: web.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rollouts-yellow
                port:
                  number: 80
